FROM python:3.11-slim

WORKDIR /app

COPY finalproject/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY finalproject ./finalproject

WORKDIR /app/finalproject
EXPOSE 8000

CMD ["python", "run.py"]
